GraphQLSwift/GraphQL

Sources/GraphQL/Type/Directives.swift

I'm trying to generate code with apollo-codegen. I received an error with the schema.json generated.
Syntax Error GraphQL (1:4) Expected <EOF>, found Name "longer"
1: No longer supported

Error when calling schema generation with introspection query

---

Sources/GraphQL/Language/AST.swift

Token ownership is now only from the parent `Token` to its `next` `Token`. This allows ARC to be able to free tokens once they are no longer used. Without this `schema.execute(...)` will continue to eat memory without giving it back as queries are served.
Hopefully no unwanted side effects to this small update.

Prevent Token linked list from leaking.

---

Sources/GraphQL/Type/Definition.swift

Required for GraphQLSwift/Graphiti#10 to build.

Make GraphQLUnionType init public

---

Sources/GraphQL/Execution/Execute.swift
Sources/GraphQL/GraphQL.swift
Sources/GraphQL/Language/AST.swift
Sources/GraphQL/Type/Definition.swift

Following up from the discussions in #13 this PR introduces the `FieldExecutionStrategy` protocol and the ability for users to specify how field execution should happen.
The introduction of the protocol has meant that quite a few more items have become `public` including the `resolveField` function. Although in the scope of this PR the `resolveField` function could remain hidden its functionality is required for any `FieldExecutionStrategy` implementation.

Introduce the FieldExecutionStrategy protocol

---

Sources/GraphQL/Utilities/TypeInfo.swift
Tests/GraphQLTests/ValidationTests/ExampleSchema.swift
Tests/GraphQLTests/ValidationTests/FieldsOnCorrectTypeTests.swift
Tests/GraphQLTests/ValidationTests/ValidationTests.swift
Tests/LinuxMain.swift

Also added some additional tests for the `FieldsOnCorrectType` validator (taken from the js reference implementation).
The commented out tests are those which are in the js reference implementation but, for whatever reason, are not passing here.
The extra testing should allow for better validator validation going forward.

Fix bug where fragment definition type stack was not correctly set

---

README.md
Sources/GraphQL/Execution/Execute.swift
Sources/GraphQL/GraphQL.swift
Sources/GraphQL/Language/AST.swift
Sources/GraphQL/Type/Definition.swift
Tests/GraphQLTests/FieldExecutionStrategyTests/FieldExecutionStrategyTests.swift
Tests/LinuxMain.swift

Use `DispatchQueue` and `DispatchGroup` to provide a simple implementation for concurrent field resolution. Some advantages to having a simple implementation is that we don't introduce any API changes and we can free the field resolvers from having to worry about things like promises and callback blocks at this point in time.
Unit tests have been added to verify the different behaviour between serial resolution (mutations) and concurrent resolution (queries). Not sure if using `usleep` is the best way to test concurrency and the `accuracy` value was pulled from thin air but it seems to work for me. I suppose CI might have different ideas.

Concurrent field resolution using Dispatch

---

Sources/GraphQL/Execution/Values.swift
Tests/GraphQLTests/StarWarsTests/StarWarsQueryTests.swift

A query containing an optional variable which is then omitted in 'variables' causes a crash at line 84 of Execution/Values.swift
For example:
query FetchHeroByEpisodeQuery($episode: String) {
hero(episode: $episode) { name } }
The additional unit test exposed the crash.
I have fixed by returning Map.null from getVariableValue when the input is .null and !(inputType is GraphQLNonNull) 
The crash was:
fatal error: unexpectedly found nil while unwrapping an Optional value
2017-06-15 11:27:52.233296+0100 xctest[66184:54165053] fatal error: unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    libswiftCore.dylib                 0x00000001052fd130 swift_reportError + 129
1    libswiftCore.dylib                 0x0000000105319b50 _swift_stdlib_reportFatalError + 60 …

Handle the case where a optional variable is omitted in a query

---

Sources/GraphQL/Error/GraphQLError.swift
Sources/GraphQL/Execution/Execute.swift
Sources/GraphQL/Language/AST.swift
Sources/GraphQL/Language/Location.swift
Sources/GraphQL/Language/Source.swift
Sources/GraphQL/Type/Definition.swift
Sources/GraphQL/Type/Directives.swift
Sources/GraphQL/Type/Schema.swift

Hopefully nothing unintentional has been exposed. Most properties are `let` and those `var`'s that might want to expose information are public only for `get`.

Expose more of the API as public

---

Sources/GraphQL/Execution/Execute.swift
Sources/GraphQL/GraphQL.swift
Sources/GraphQL/Instrumentation/DispatchQueueInstrumentationWrapper.swift
Sources/GraphQL/Instrumentation/Instrumentation.swift
Sources/GraphQL/Language/Parser.swift
Sources/GraphQL/PersistedQueries/PersistedQueries.swift
Sources/GraphQL/Validation/Validate.swift
Tests/GraphQLTests/InstrumentationTests/InstrumentationTests.swift
Tests/GraphQLTests/PersistedQueriesTests/PersistedQueriesTests.swift
Tests/LinuxMain.swift

**Note:** Currently implemented on top of #20 so will include some extra noise at the moment.
Takes a different approach that what I first proposed in #12.
* Deliberately kept the responsibility for performing the parsing and validating of any persisted query to `PersistedQueryRetrieval` implementations.
* Attempts to keep the calling side similar to the existing `graphql` function.
Due to the decision to put parsing and validating queries as the responsibility of any `PersistedQueryRetrieval` implementation we have to make a version of `parse()` and `validate()` public. However this does mean that implementations are free to decide when, and if, parsing and validation happens.
This means that an implementation is free to be able to only parse and validate a persisted query once when its …

Introduce persisted queries

---

README.md

I have updated the SPM manifest example in README.
I think it is reasonable because GraphQL package itself is already compatible with Swift 4 and swift-tools-version 4.0.

Update SPM manifest example in README

---

Sources/GraphQL/Language/Lexer.swift
Tests/GraphQLTests/LanguageTests/LexerTests.swift

Thank you for library!
We are using it for mutating and we can pass long strings like 60k. And it works very slow as indexing over swift strings is not constant time operation. So had to switch to indexes not to subscript from start every time
e.g. for 60k before changes 5 minutes, and after changes 0.013 sec

Fix performance of readString

---

Package.resolved
Sources/GraphQL/Execution/Execute.swift
Tests/GraphQLTests/FieldExecutionStrategyTests/FieldExecutionStrategyTests.swift

The implementation of completeValueCatchingError wasn't handling failed futures correctly.
It had an expectation that any failed future should only fail with GraphQLError (and would fatalError() otherwise) rather than any Error which could then be converted to a GraphQLError.

Fix 'completeValueCatchingError' to handle failed futures

---

.travis.yml
Package.resolved
Sources/GraphQL/Map/AnyCoder.swift
Sources/GraphQL/Map/Map.swift
Sources/GraphQL/Map/MapCoder.swift
Sources/GraphQL/Map/MapSerialization.swift
Sources/GraphQL/Type/Introspection.swift
Tests/LinuxMain.swift

Currently boolean are serialized as Int: `0` for `false` and `1` for `true`.
It is now serialized with `true` or `false`.
This pull request also fix Linux build. Checking `DEPLOYMENT_RUNTIME_SWIFT` was not sufficient so `os(Linux)` must be added for this specific build.

Fix boolean serialization

---

Sources/GraphQL/Language/AST.swift
Sources/GraphQL/Language/Lexer.swift
Tests/GraphQLTests/LanguageTests/LexerTests.swift

This PR addresses #64 "GraphQL doesn't support 'Blockstrings' which are often used in Descriptions".
There are multiple ways to implement this support and I tried to pick one that matches the existing style of lexing/parsing.  Lots of tests are included, though I'm sure more could be thought of.
There's one piece that I just noticed is missing: support for escaped Blockstrings  `\"""`
I'm out of time for this project and don't actually need those (yet), so I'm going to punt on that for now.  Shouldn't be terribly difficult, but… ¯\_(ツ)_/¯.
I hope you find these contributions acceptable in form and substance.  Feel free to let me know if there's things you'd prefer to be done differently.
All my work has been done on macOS 10.15.6 using Xcode 12b5, so I will be interested to see if this …

Add Blockstrings support

---

Sources/GraphQL/Language/AST.swift
Sources/GraphQL/Language/Lexer.swift
Tests/GraphQLTests/LanguageTests/LexerTests.swift

Modified the blockstring support implementation to be closer to canonical js implementation, and also add \””” support as well as a few more tests.

Modify blockstring support to be closer to canonical js implementation

---

Sources/GraphQL/Language/AST.swift
Sources/GraphQL/Language/Lexer.swift
Sources/GraphQL/Language/Parser.swift
Tests/GraphQLTests/LanguageTests/ParserTests.swift
Tests/GraphQLTests/LanguageTests/SchemaParserTests.swift

This addresses #63 "GraphQL parser does not support optional `Description`s"
This adds description support via `parseTypeSystemDefinition`:
- `SchemaDefinition`
- `ScalarTypeDefintion`
- `ObjectTypeDefinition`
- `InterfaceTypeDefinition`
- `UnionTypeDefinition`
- `EnumTypeDefinition`
- `InputObjectTypeDefinition`
- `DirectiveDefinition`
others:
- `EnumValueDefinition`
- `FieldDefinition`
- `InputValueDefinition`
This also supports multi-line Descriptions now that the Blockstring PRs #65 and #68 have been merged in, and this includes several tests for those.
All my work has been done on macOS 10.15.6 using Xcode 12b5.
Fixes #63

Add support for optional Description for those objects which allow it

---

.github/workflows/build.yml
Sources/GraphQL/Type/Definition.swift

This adds support for recursive inputs (inputs that reference themselves). For example, the following is now a valid input definition:
```
input BoolExp {
and: [BoolExp]
or: [BoolExp]
val: Bool
}
```
This builds on the Type and Interface recursion support (via `TypeReference`), by extending that functionality to Inputs as well.
It also renames a few Input Field types to be more consistent with the equivalent Type Field types

Adds support for reference types on Input fields

---

Sources/GraphQL/Type/Definition.swift
Sources/GraphQL/Type/Schema.swift
Tests/GraphQLTests/TypeTests/GraphQLArgumentDefinitionTests.swift
Tests/GraphQLTests/TypeTests/GraphQLSchemaTests.swift

Updated `assert(object:implementsInterface:schema:)` to work like [canonical js](https://github.com/graphql/graphql-js/blob/7b3241329e1ff49fb647b043b80568f0cf9e1a7c/src/type/validate.js#L405) when validating that additional field arguments must not be required.
Before, the assertion:
* would fail if an object's field had a required argument, even when it matched a required argument from the interface.
Now, the assertion:
* will succeed when the object's field has required arguments matching the interface
* will succeed when the object's field has additional arguments not found in the interfaces, so long as the arguments are nullable or have default values.

Fixed asserting an object implements an interface with required field arguments

---

Sources/GraphQL/Language/AST.swift
Sources/GraphQL/Language/Kinds.swift
Sources/GraphQL/Language/Parser.swift
Tests/GraphQLTests/LanguageTests/ParserTests.swift

Null value literals can now be parsed in queries
```graphql
{ fieldWithArg(arg: null) }
```
And in type definitions
```graphql
type SomeType {
fieldWithDefaultArg(arg: String = null): String
}
```
Added tests for parsing field arguments
Added tests for parsing directives

Added support for parsing null value literals

---

Package.resolved
Package.swift
Sources/GraphQL/Execution/Execute.swift
Sources/GraphQL/Map/Map.swift
Sources/GraphQL/Map/MapCoder.swift
Sources/GraphQL/Map/MapSerialization.swift
Sources/GraphQL/Subscription/Subscribe.swift
Sources/GraphQL/Utilities/NIO+Extensions.swift
Sources/GraphQL/Utilities/ValueFromAST.swift
Tests/GraphQLTests/StarWarsTests/StarWarsQueryTests.swift

Fixes #60 
This was implemented by adding the Swift Collections dependency and adjusting most ordinary `Dictionary` instances to `OrderedDictionary`.
Graphiti will require a PR to be compatible, which I will submit shortly.
Thanks!!

Preserves result order

---

.github/workflows/build.yml
Sources/GraphQL/Execution/Values.swift
Sources/GraphQL/Map/Map.swift
Sources/GraphQL/Map/MapSerialization.swift
Sources/GraphQL/Type/Definition.swift
Sources/GraphQL/Utilities/ValueFromAST.swift
Tests/GraphQLTests/InputTests/InputTests.swift
Tests/GraphQLTests/MapTests/MapTests.swift

This adds support to differentiate between *explicitly providing the literal value null* and *implicitly not providing a value at all*, as described in the spec [here](https://spec.graphql.org/June2018/#sec-Null-Value) and [here](https://spec.graphql.org/draft/#sec-Input-Objects.Input-Coercion).
To do so, an `undefined` case is added to the Map enum, and argument parsing uses this value when expected arguments are not provided. Field default values now override only undefined maps.
The end result is that Map encoding works like JSON where a field with a literal `null` is contained by the decoding container, whereas an un-provided value is not. From here, custom object decodings can adjust functionality based on the two situations. For example:
```swift
struct Obj : Codable {
let field1: …
```

Input object null vs undefined

---

Sources/GraphQL/GraphQL.swift

Starting with the August 28, 2021 Swift.org nightly development snapshot, there is currently a compiler crasher when building Swift code that contains a default parameter of `Void()` with debug symbols enabled. This has been reported as [SR-15181](https://bugs.swift.org/browse/SR-15181) and the Swift team is aware of it.
An easy way to work around this is to make the stylistic change from `= Void()` to `= ()` in these default parameters. That no longer triggers the compiler crasher. I've done that here, because GraphQL was the only project in our dependencies that had an example of this specific crasher.
This crasher did not make its way into the 5.5 release, and most likely will be fixed before the next stable release, so I understand if you're hesitant to make this stylistic change …

Changing Void() default parameters to avoid a recent compiler crasher

---

Sources/GraphQL/Execution/Execute.swift
Sources/GraphQL/Execution/Values.swift
Sources/GraphQL/Map/Map.swift
Sources/GraphQL/Subscription/Subscribe.swift
Sources/GraphQL/Utilities/IsValidValue.swift
Sources/GraphQL/Utilities/ValueFromAST.swift
Tests/GraphQLTests/InputTests/InputTests.swift

This is a follow-up to https://github.com/GraphQLSwift/GraphQL/pull/87. That PR added support to differentiate between *explicitly providing the literal value null* and *implicitly not providing a value at all* in input objects provided in the arguments. This merge request extends that functionality to input objects in variables and non-object arguments.
It also fixes a bug with not pre-validating argument inputs against their type (for example, passing null to a non-null parameter would passed null all the way into the resolver). It also removes force-casts to harden against server-wide fatal errors.

Variable and argument null vs undefined

---

README.md
Sources/GraphQL/GraphQL.swift
Sources/GraphQL/Map/GraphQLJSONEncoder.swift
Sources/GraphQL/Map/Map.swift
Sources/GraphQL/Utilities/ASTFromValue.swift
Tests/GraphQLTests/MapTests/MapTests.swift

If you encode a `GraphQLResult` with an ordinary `JSONEncoder`, there are no guarantees that the field order will match the query, violating the [GraphQL spec](https://spec.graphql.org/June2018/#sec-Serialized-Map-Ordering). 
This PR adds a `GraphQLJSONEncoder` type that will ensure that order is preserved when a Map is encoded. It is exactly the same as Foundation's `JSONEncoder`, but uses `OrderedDictionary` everywhere `Dictionary` was used.

Fixes Encoded JSON Result Ordering

---

Package.resolved
Sources/GraphQL/GraphQLRequest.swift

This type is not used within in this package, but is useful for clients to model the [standard execution request information](https://spec.graphql.org/October2021/#sec-Execution)

Adds GraphQLRequest type

---

Sources/GraphQL/GraphQL.swift
Sources/GraphQL/Subscription/EventStream.swift
Tests/GraphQLTests/HelloWorldTests/HelloWorldTests.swift
Tests/GraphQLTests/SubscriptionTests/SimplePubSub.swift
Tests/GraphQLTests/SubscriptionTests/SubscriptionSchema.swift
Tests/GraphQLTests/SubscriptionTests/SubscriptionTests.swift

This adds support for Swift concurrency by adding new top-level async public APIs.
It also adds a Swift concurrency-based `EventStream`. This allows us to directly test the subscription functionality within this package, and allows clients to use GraphQL subscriptions without coding custom EventStreams (which typically required drivers like [GraphQLRxSwift](https://github.com/GraphQLSwift/GraphQLRxSwift))
Long term, we probably want to remove the `EventStream` workaround and just use the swift concurrency types by default. This has been left as a future task though, because it would require a breaking API change and require all clients to be using swift versions that support concurrency.

Swift Concurrency Support

---

Sources/GraphQL/Subscription/EventStream.swift
Tests/GraphQLTests/SubscriptionTests/SubscriptionTests.swift

Addressing issue #101 
- Updated `.mapStream` and `.filterStream` to catch thrown error and pass it to the next/transformed stream
- Updated `.mapStream` and `.filterStream` to call `continuation.finish()` when the source stream ended/finished with no error
- Updated `.mapStream` and `.filterStream` to cancel `Task` used to consume source stream when it has been terminated
- Updated SubscriptionsTest's `testNoTriggerAfterDone `, `testErrorDuringSubscription `, and `testArguments` to not discard the `ConcurrentEventStream` which would close all `Task` used to perform transformations of element (Previously was not an issue because of the leak that keep the `Task` alive).

Fixing issues with ConcurrentEventStream from #101

---

Package.resolved
Sources/GraphQL/GraphQL.swift
Sources/GraphQL/Language/Visitor.swift
Sources/GraphQL/Validation/SpecifiedRules.swift
Sources/GraphQL/Validation/Validate.swift

Following #98,
I was looking for a way to specify custom validation rules and use them to validate GraphQL requests, which would allow something like [GraphQL Query Cost Analysis](https://www.npmjs.com/package/graphql-cost-analysis), [GraphQL Depth Limit](https://www.npmjs.com/package/graphql-depth-limit), etc.

Making validate with validation rules public

---

.github/workflows/build.yml
Tests/LinuxMain.swift

As with Graphiti, GraphQL does not have working Linux tests.
This PR resolves this.

Add working Linux tests

---

README.md

This is just to help others use this package as we [pitch it for inclusion in SSWG](https://forums.swift.org/t/pitch-graphql/59554)

Adds usage guide in readme

---

README.md
SECURITY.md

These are just a few more documentation changes needed to conform to the [SSWG incubation minimal requirements](https://github.com/swift-server/sswg/blob/main/process/incubation.md#minimal-requirements)

doc: Adds security and conduct details for sswg

---

.github/workflows/build.yml
Sources/GraphQL/Error/SyntaxError.swift
Sources/GraphQL/Execution/Execute.swift
Sources/GraphQL/GraphQL.swift
Sources/GraphQL/Language/Lexer.swift
Sources/GraphQL/Language/Location.swift
Sources/GraphQL/Language/Parser.swift
Sources/GraphQL/Map/AnySerialization.swift
Sources/GraphQL/Map/Map.swift
Sources/GraphQL/Map/MapSerialization.swift
Sources/GraphQL/Subscription/Subscribe.swift
Sources/GraphQL/SwiftUtilities/SuggestionList.swift
Sources/GraphQL/Type/Schema.swift
Sources/GraphQL/Utilities/ASTFromValue.swift
Sources/GraphQL/Utilities/NIO+Extensions.swift
Sources/GraphQL/Utilities/TypeFromAST.swift
Sources/GraphQL/Utilities/TypeInfo.swift
Sources/GraphQL/Validation/Rules/FieldsOnCorrectTypeRule.swift
Sources/GraphQL/Validation/Validate.swift
Tests/GraphQLTests/InputTests/InputTests.swift
Tests/GraphQLTests/LanguageTests/SchemaParserTests.swift
Tests/GraphQLTests/SubscriptionTests/SubscriptionSchema.swift
Tests/GraphQLTests/SubscriptionTests/SubscriptionTests.swift

This MR removes a significant number of `fatalError`s, force-unwraps, force-trys, and force-casts. This is to improve code safety and be more in compliance with the [SSWG Technical Best Practices](https://github.com/swift-server/sswg/blob/main/process/incubation.md#technical-best-practices).
Some force operations remain, but they are mainly where throwing is not possible (top level literals), or in code mostly copied from a specific source. Examples of this include Encoder/Decoders that are based on Foundation's JSON coders, and Visitor based on the graphql-js reference implementation.

Code safety improvements

---

Sources/GraphQL/Execution/Execute.swift

This was preventing custom Scalars from representing items using `Map.null`. In the case where the value cannot be serialized, the serialize method itself should throw an error (not return null).

fix: Removes null serialization check.

---

Sources/GraphQL/Type/Schema.swift
Tests/GraphQLTests/TypeTests/GraphQLSchemaTests.swift

This PR adds enhances TypeReference handling in the following ways:
1. Changes logic to ensure that TypeReferences are replaced during typeMapReduction
2. Adds logic to ensure that all TypeReferences in instantiated Schemas have been replaced by the actual types. In the case where they are not, the schema initalizer throws an error.
Tests are added too

TypeReference improvements

---

Sources/GraphQL/Language/Source.swift

While this doesn't impact UTF8 strings built up in Swift, Strings decoded from data (like through Vapor, for example) may not be marked as UTF8, which makes the lexer UTF8 conversions very expensive. In evaluation of 450kb requests, performance improved from 27min to 5sec with this adjustment.

Optimizes parsing of large non-UTF8 queries

---

Sources/GraphQL/Language/AST.swift
Sources/GraphQL/Language/Kinds.swift
Sources/GraphQL/Language/Parser.swift
Tests/GraphQLTests/LanguageTests/SchemaParserTests.swift

This PR adds support for `extend Schema` syntax used with Apollo Federation.

Extend Schema Support

---

.github/workflows/build.yml

It appears that on GitHub `ubuntu-latest` is Ubuntu 22.04 and there are no Swift downloads for it for older versions prior to 5.7 https://www.swift.org/download/. So for testing `5.4`, `5.5` and `5.6` I suggest using an older version of Ubuntu that Swift has downloads for.

update linux workflows

---

Sources/GraphQL/Error/GraphQLError.swift

Small fix for the `GraphQLError` decoder that allows correctly decoding an error with a missing `location` or `path` field by defaulting to empty.

fix: correctly handle missing GraphQLError location/path on decode

---

Sources/GraphQL/Language/AST.swift
Sources/GraphQL/Language/Kinds.swift
Sources/GraphQL/Language/Lexer.swift
Sources/GraphQL/Language/Parser.swift
Tests/GraphQLTests/LanguageTests/ParserTests.swift
Tests/GraphQLTests/LanguageTests/SchemaParserTests.swift
Tests/GraphQLTests/LanguageTests/schema-kitchen-sink.graphql

- Adds ampersand support from #73
- Adds support for `extend` for `interface`, `scalar`, `union`, `enum` and `input`
- Adds support for undefined types ie `extend enum Site`
- Adds support for `repeatable` on directives
- Adds support for leading pipe on enum/directives
- Updates kitchen sink schema to match https://github.com/graphql/graphql-js/blob/main/src/__testUtils__/kitchenSinkSDL.ts

Update Schema Kitchen Sink Parsing + Tests

---

Sources/GraphQL/Execution/Execute.swift
Sources/GraphQL/Utilities/NIO+Extensions.swift
Tests/GraphQLTests/FieldExecutionStrategyTests/FieldExecutionStrategyTests.swift

Exposed a bug in mocks for `FieldExecutionStrategyTests` affecting `testSerialFieldExecutionStrategyWithMultipleFieldErrors`.
Prior to the change, the test appeared to be serial because the mocking framework blocked execution *before* returning the future - as opposed to blocking execution on the EventLoop.
The `SerialFieldExecutionStrategy` execution resolution implementation used NIO's `.flatten` on an array of futures (which all executed concurrently). However, the creation of these futures was thread blocked specifically in the tests, leading to the appearance of serial execution.
These changes correct the catalyzing test mock as well as `SerialFieldExecutionStrategy` such that it resolves fields in a truly serial fashion.

fix: Serial Execution Strategy

---

.github/workflows/build.yml
Sources/GraphQL/Error/GraphQLError.swift
Sources/GraphQL/Execution/Values.swift
Sources/GraphQL/Language/Parser.swift
Sources/GraphQL/Map/GraphQLJSONEncoder.swift
Sources/GraphQL/Map/Map.swift
Sources/GraphQL/Utilities/NIO+Extensions.swift
Sources/GraphQL/Utilities/ValueFromAST.swift
Tests/GraphQLTests/LanguageTests/ParserTests.swift
Tests/GraphQLTests/SubscriptionTests/SubscriptionTests.swift

This adds an extensions property to `GraphQLError`, resolving https://github.com/GraphQLSwift/GraphQL/issues/127
It also makes other minor fixes, including changing expectation waits to avoid warnings and removing unused encoder cases that also produced warnings.
Due to formatting changes, it is probably easiest to review commit-by-commit.
This is a backwards-compatible minor change.

Adds GraphQLError extensions

---

Sources/GraphQL/GraphQLRequest.swift

This just adds a convenience function to get the operation type from a request.

feature: Adds request operation type function

---

Sources/GraphQL/Language/Printer.swift
Tests/GraphQLTests/FederationTests/FederationTests.swift
Tests/GraphQLTests/LanguageTests/PrinterTests.swift

Ported printer functions from https://github.com/graphql/graphql-js/blob/main/src/language/printer.ts with the goal of using it with federation features. Currently users need to use `.setFederatedSDL(to: <String>)` in the schema builder in Graphiti and this feels like a step toward removing that requirement. 
Still need to port printString and printBlockString functions from the js implementation but that ran into some complications and I would prefer to do that in a future PR. 
I'm still unsure about how to expose this in Graphiti and get the document type to `GraphQLSchema`.

Port Printer from graphql-js

---

Sources/GraphQL/Language/AST.swift
Sources/GraphQL/Language/Kinds.swift
Sources/GraphQL/Language/Visitor.swift
Sources/GraphQL/Validation/Rules/NoUnusedVariablesRule.swift
Sources/GraphQL/Validation/Validate.swift
Tests/GraphQLTests/ValidationTests/NoUnusedVariablesRuleTests.swift

Fixes https://github.com/GraphQLSwift/GraphQL/issues/61

Fixes NoUnusedVariablesRule false positive

---

Sources/GraphQL/Error/GraphQLError.swift
Sources/GraphQL/Language/AST.swift
Sources/GraphQL/Language/Kinds.swift
Sources/GraphQL/Language/Visitor.swift
Tests/GraphQLTests/LanguageTests/VisitorTests.swift

This adds editing support to the AST Visitor system. In addition, it also:
- Adds all graphql-js visitor tests cases, both for editing and for normal visitor operation
- Fixes a bug where the Visitor would not visit all Directive, ListType, or ListValue properties
- Fixes a bug where Visitor path would be generated incorrectly
- Improves Visitor null safety

Visitor Fixes and Editing Support

---

Sources/GraphQL/Type/Definition.swift
Sources/GraphQL/Type/Directives.swift
Sources/GraphQL/Type/Introspection.swift
Sources/GraphQL/Validation/Rules/Custom/NoDeprecatedCustomRule.swift
Sources/GraphQL/Validation/Rules/Custom/NoSchemaIntrospectionCustomRule.swift
Tests/GraphQLTests/ValidationTests/NoDeprecatedCustomRuleTests.swift

This adds the custom validation rules:
- NoDeprecatedCustomRule
- NoSchemaIntrospectionCustomRule
Note that they are not added to the specified list of rules, which matches the usage in graphql-js
As part of this work, deprecated support was added to Arguments and Input Object Fields.

Adds Custom Validation Rules

---

Sources/GraphQL/Language/BlockString.swift
Sources/GraphQL/Language/CharacterClasses.swift
Sources/GraphQL/Language/Parser.swift
Sources/GraphQL/Language/PrintString.swift
Sources/GraphQL/Language/Printer.swift
Tests/GraphQLTests/LanguageTests/BlockStringTests.swift
Tests/GraphQLTests/LanguageTests/PrintStringTests.swift
Tests/GraphQLTests/LanguageTests/SchemaParserTests.swift
Tests/GraphQLTests/LanguageTests/SchemaPrinterTests.swift
Tests/GraphQLTests/LanguageTests/schema-kitchen-sink.graphql

This makes the following minor fixes to the Printer and Parser to support SDL functionality:
1. Schema extension parser correctly captures operations
1. Description printing matches reference implementation
1. Parser correctly errors on empty `extend` blocks
1. Parser correctly errors when disallowed descriptions are provided.

Fixes Parser & Printer for SDL Functionality

---

Sources/GraphQL/Execution/Execute.swift
Sources/GraphQL/Type/Directives.swift
Sources/GraphQL/Validation/Rules/Custom/NoDeprecatedCustomRule.swift
Tests/GraphQLTests/FieldExecutionStrategyTests/FieldExecutionStrategyTests.swift

Minor tweaks to fix compiler warnings

Fixes compiler warnings

---

.github/workflows/build.yml
Sources/GraphQL/Validation/Rules/KnownDirectivesRule.swift

I was digging into why this PR failed in Swift 5.4: https://github.com/GraphQLSwift/Graphiti/pull/134 and noticed that the issue was actually in package. This PR fixes a shadow variable issue:
`Previous shadow copy into locations in the same scope!` https://github.com/GraphQLSwift/Graphiti/actions/runs/8103942873/job/22211259878?pr=134#step:4:238
Also added 5.4 as part of the GitHub workflow.

Fix issue with shadow variables in Swift 5.4

---

Sources/GraphQL/Language/Parser.swift
Sources/GraphQL/Language/Printer.swift
Sources/GraphQL/Subscription/EventStream.swift
Tests/GraphQLTests/SubscriptionTests/SimplePubSub.swift

This enables custom query parsing logic as well as printing SDLs for existing schemas. This could be helpful for federation support.

Exposes `parse` and `print` functions

---

Sources/GraphQL/Type/Definition.swift
Sources/GraphQL/Type/Directives.swift
Sources/GraphQL/Type/Introspection.swift
Sources/GraphQL/Utilities/IsValidValue.swift
Sources/GraphQL/Utilities/ValueFromAST.swift
Sources/GraphQL/Validation/Rules/ValuesOfCorrectTypeRule.swift
Tests/GraphQLTests/ExecutionTests/OneOfTests.swift
Tests/GraphQLTests/ValidationTests/ExampleSchema.swift
Tests/GraphQLTests/ValidationTests/ValuesOfCorrectTypeRuleTests.swift

This adds support for the `oneOf` input object directive and the `specifiedBy` scalar directive

Adds `oneOf` and `specifiedBy` directives

---

.github/workflows/build.yml

This changes the MacOS CI from using the `latest` XCode to `latest-stable` to avoid going to v16, which comes with Swift 6.0.0. This resolves the issues observed here: https://github.com/GraphQLSwift/Graphiti/pull/137#issuecomment-2177314720
It also adds Swift 5.9 and 5.10 to the Linux test matrix

ci: Changes xcode version to latest stable

---

Sources/GraphQL/Type/Introspection.swift
Sources/GraphQL/Utilities/ASTFromValue.swift
Tests/GraphQLTests/TypeTests/IntrospectionTests.swift

Input object and boolean default values are represented correctly in introspection.
Previous to this change, default boolean values were reported as `null`, and input objects were represented in JSON format (`{"a": "b"}` instead of `{ a: "b" }`).

Fixes default value introspection

---

Sources/GraphQL/Type/Scalars.swift
Tests/GraphQLTests/TypeTests/ScalarTests.swift

This adjusts the default GraphQL scalar types to correctly intake and output objects, and adds tests.
Fixes https://github.com/GraphQLSwift/GraphQL/issues/152

Fixes scalar type serialization

---

.github/workflows/build.yml
Package.resolved
Package.swift
README.md
Sources/GraphQL/GraphQL.swift
Sources/GraphQL/Subscription/EventStream.swift
Tests/GraphQLTests/HelloWorldTests/HelloWorldTests.swift
Tests/GraphQLTests/SubscriptionTests/SimplePubSub.swift
Tests/GraphQLTests/SubscriptionTests/SubscriptionSchema.swift
Tests/GraphQLTests/SubscriptionTests/SubscriptionTests.swift

- Set Swift 5.8 as the minimum supported version. 
- Removed CI job for Ubuntu 20.04.
-  Bumped `swift-nio` and `swift-collections` versions on the manifest.

Set Swift 5.8 as the minimum supported version

---

Sources/GraphQL/Type/Scalars.swift
Tests/GraphQLTests/TypeTests/ScalarTests.swift

This is because MapCoder round-trips of Bools result in Number types. This is hard to avoid since it gets put into an NSObject container and there is no NSBool type.
Note that query validation will still disallow directly passing numeric values into boolean arguments as tested here: https://github.com/GraphQLSwift/GraphQL/blob/0dfa0d9b0ed3abb922632908e269186398bba8d3/Tests/GraphQLTests/ValidationTests/ValuesOfCorrectTypeRuleTests.swift#L412 Instead this simply allows numeric Swift map objects to be interpreted as GraphQLBool types.
Fixes https://github.com/GraphQLSwift/GraphQL/issues/155

Allows numeric values to be parsed as GraphQLBools

---

Sources/GraphQL/GraphQL.swift
Sources/GraphQL/Subscription/EventStream.swift
Sources/GraphQL/Type/Definition.swift
Tests/GraphQLTests/SubscriptionTests/SimplePubSub.swift
Tests/GraphQLTests/SubscriptionTests/SubscriptionTests.swift

Fixes minor formatting issues that are caught by the CI

Formatting

---

.github/workflows/build.yml
Package.resolved
Sources/GraphQL/Instrumentation/Instrumentation.swift
Sources/GraphQL/Map/AnyCoder.swift
Sources/GraphQL/Map/MapCoder.swift
Tests/GraphQLTests/InstrumentationTests/InstrumentationTests.swift

This PR makes the minimal changes needed for Android support.
~It won't build for Android yet until a `swift-nio` release is cut that includes https://github.com/apple/swift-nio/pull/3033, but if you switch the `swift-nio` dependency to `branch: "main"`, test cases will pass (e.g., by running `skip android test` or using the [swift-android-action](https://github.com/marketplace/actions/swift-android-action) github action).~
It builds and passes all the tests on Android as of [swift-nio 2.78.0](https://github.com/apple/swift-nio/releases/tag/2.78.0) .

Android support

---

.github/workflows/build.yml
Sources/GraphQL/Execution/Execute.swift
Sources/GraphQL/Execution/Values.swift
Sources/GraphQL/GraphQL.swift
Sources/GraphQL/Map/Map.swift
Sources/GraphQL/Map/Number.swift
Sources/GraphQL/Utilities/NIO+Extensions.swift
Tests/GraphQLTests/LanguageTests/LexerTests.swift
Tests/GraphQLTests/SubscriptionTests/SubscriptionTests.swift

This removes warnings and adds Swift 6 compatibility CI checks.

Swift 6 Compatibility

---

Sources/GraphQL/GraphQLRequest.swift

This simply marks `GraphQLResult` as Sendable, which is convenient when conforming downstream APIs to strict concurrency.

`GraphQLResult` marked Sendable
